- cotisations:
  # Model: List all cotisations amounts, begin and end dates with adherent name and town
  name: Cotisations
  description: Export de l'état des cotisations pour l'ensemble des adhérents
  filename: galette_cotisations.csv
  query: |-
    SELECT nom_adh, prenom_adh, ville_adh, montant_cotis, date_debut_cotis, date_fin_cotis 
      FROM galette_cotisations 
      INNER JOIN galette_adherents 
        ON (galette_cotisations.id_adh=galette_adherents.id_adh)
  headers:
    - Name
    - Surname
    - Town
    - Amount
    - Begin date
    - End date
  separator: ;
  quote: \"

- adherents:
  # Les des tous les adhérents à jour
  name: Adherents
  description: Export des adhérents à jour
  filename: galette_adherents.csv
  query: |-
    SELECT Name, Surname from galette_adherents;
  headers:
    - Nom
    - Prénom
  separator: ;
  quote: \"
  